name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run install
      run: npm install
    - name: Run build 
      run: npm run build 
    - name: Run test 
      run: npm run test 
